version: "3.1"
services:
  api:
    image: testimage5
    ports: 
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - mysql-compose-network
    links: 
      - link-db
  link-db:
    image: mysql:5.5
    container_name: db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - mysql-compose-network
networks: 
  mysql-compose-network:
    driver: bridge